#include "flamoris/runtime/native.hpp"
#include <catch_amalgamated.hpp>
#include <fstream>

using namespace flamoris::runtime;
namespace {
class FailingCompute : public ComputeImplementation {
    std::unique_ptr<ComputeImplementation> cpu = make_cpu_compute();
    std::size_t count = 0;

  public:
    const ComputeDevice &device() const noexcept override { return cpu->device(); }
    Result<std::vector<float>> matvec(std::span<const float> m, std::size_t r, std::size_t c,
                                      std::span<const float> x) override {
        if (++count == 9)
            return Result<std::vector<float>>::failure(
                ErrorEnvelope::make(ErrorCode::native_execution_failure));
        return cpu->matvec(m, r, c, x);
    }
    Result<std::vector<float>> attention(std::span<const float> q, std::span<const float> k,
                                         std::span<const float> v, std::size_t p,
                                         std::size_t d) override {
        return cpu->attention(q, k, v, p, d);
    }
    ComputeReceipt receipt() const noexcept override { return cpu->receipt(); }
    Result<void> synchronize() override { return cpu->synchronize(); }
};
constexpr auto checksum = "5cd5a0bacb4cce1efd801fe2a4d7c1347467538ef6e393b37d955d2499ef74e2";
std::shared_ptr<const TinyModel> model() {
    auto result = TinyModel::load(std::filesystem::path(FLAMORIS_SOURCE_DIR) /
                                      "fixtures/native/tiny-causal-v1.bin",
                                  checksum);
    REQUIRE(result);
    return result.value();
}
std::unique_ptr<NativeSession> session(NativeOptions options = {},
                                       std::string_view prompt = "Hello 日本語") {
    auto result = NativeSession::create(model(), make_cpu_compute(), {}, {}, prompt, options);
    REQUIRE(result);
    return std::move(result).value();
}
void prefill(NativeSession &native) {
    while (native.state().stage == NativeStage::prefill)
        REQUIRE(native.step(3));
}
void finish(NativeSession &native) {
    while (native.state().stage == NativeStage::prefill ||
           native.state().stage == NativeStage::decode)
        REQUIRE(native.step(3));
}
} // namespace
TEST_CASE("B-REAL01 registered fixture checksum CPU arithmetic cached and uncached",
          "[native][cpu]") {
    REQUIRE_FALSE(TinyModel::load(std::filesystem::path(FLAMORIS_SOURCE_DIR) /
                                      "fixtures/native/tiny-causal-v1.bin",
                                  std::string(64, '0')));
    auto cpu = make_cpu_compute();
    const std::vector<float> matrix{1, 2, 3, 4, 5, 6}, input{2, 3, 4};
    auto product = cpu->matvec(matrix, 2, 3, input);
    REQUIRE(product);
    REQUIRE(product.value() == std::vector<float>{20, 47});
    auto attention = cpu->attention(std::vector<float>{0, 0}, std::vector<float>{1, 2, 3, 4},
                                    std::vector<float>{2, 4, 6, 8}, 2, 2);
    REQUIRE(attention);
    REQUIRE(attention.value() == std::vector<float>{4, 6});
    auto weights = model();
    std::vector<TokenId> ids{256, 72, 105, 230, 151, 165};
    std::vector<float> keys, values;
    for (std::size_t i = 0; i < ids.size(); ++i) {
        auto cached = weights->evaluate(ids[i], keys, values, *cpu);
        auto full = weights->uncached(std::span<const TokenId>(ids).first(i + 1), *cpu);
        REQUIRE(cached);
        REQUIRE(full);
        REQUIRE(cached.value() == full.value());
        REQUIRE(keys.size() == (i + 1) * 8);
    }
    // Independent binary64 full-sequence reference, generated by fixtures/native/reference.py.
    auto oracle = weights->uncached(ids, *cpu);
    REQUIRE(oracle);
    const std::array<float, 8> expected{
        -0.08352722724478184F, 0.07421349080884858F, -0.021961120603395487F, 0.0766954687121905F,
        0.029136076165365423F, 0.04481265447278667F, 0.1114019640076204F,    0.1674346853303179F};
    for (std::size_t i = 0; i < expected.size(); ++i)
        REQUIRE(oracle.value()[i] == Catch::Approx(expected[i]).margin(2.0e-7).epsilon(1.0e-5));
    REQUIRE(std::max_element(oracle.value().begin(), oracle.value().end()) -
                oracle.value().begin() ==
            242);
    auto native = session();
    prefill(*native);
    REQUIRE(native->causal_state().logits.size() == 258);
    REQUIRE(native->retained_bytes() < native->reserved_state_bytes());
    REQUIRE(native->step());
    REQUIRE(native->causal_state().pending);
    REQUIRE(native->causal_state().evaluated.size() == native->causal_state().input.size());
    REQUIRE(native->step());
    REQUIRE(native->causal_state().evaluated.size() == native->causal_state().input.size() + 1);
}
TEST_CASE("B-REAL02 B-REAL06 complete sampled state survives each safe-point pause",
          "[native][cpu]") {
    NativeOptions options;
    options.max_output_tokens = 24;
    options.sampling.temperature = 0.7F;
    options.sampling.repetition_penalty = 1.2F;
    options.sampling.top_k = 15;
    options.sampling.seed = 193;
    auto uninterrupted = session(options), paused = session(options);
    while (uninterrupted->state().stage == NativeStage::prefill ||
           uninterrupted->state().stage == NativeStage::decode) {
        auto expected = uninterrupted->step(2);
        auto actual = paused->step(2);
        REQUIRE(expected);
        REQUIRE(actual);
        REQUIRE(paused->causal_state() == uninterrupted->causal_state());
        if (!actual.value().complete) {
            auto snapshot = paused->causal_state();
            auto generation = paused->pause();
            REQUIRE(generation);
            REQUIRE_FALSE(paused->step());
            REQUIRE(paused->causal_state() == snapshot);
            auto pins = paused->state().pins;
            auto changed = pins;
            changed.tokenizer += ":new";
            REQUIRE_FALSE(paused->resume(changed, generation.value()));
            changed = pins;
            changed.processor += ":new";
            REQUIRE_FALSE(paused->resume(changed, generation.value()));
            REQUIRE_FALSE(paused->resume(pins, generation.value() + 1));
            REQUIRE(paused->resume(pins, generation.value()));
            REQUIRE_FALSE(paused->resume(pins, generation.value()));
        }
    }
    REQUIRE(paused->causal_state() == uninterrupted->causal_state());
    REQUIRE(paused->causal_state().rng_draws > 0);
}
TEST_CASE("B-REAL03 segment failure stop and explicit physical state release", "[native][cpu]") {
    auto created =
        NativeSession::create(model(), std::make_unique<FailingCompute>(), {}, {}, "failure");
    REQUIRE(created);
    auto native = std::move(created).value();
    REQUIRE_FALSE(native->release());
    REQUIRE_FALSE(native->step(4));
    REQUIRE(native->state().stage == NativeStage::failed);
    REQUIRE_FALSE(native->state().valid);
    REQUIRE_FALSE(native->pause());
    REQUIRE(native->release());
    REQUIRE(native->state().stage == NativeStage::released);
    REQUIRE_FALSE(native->step());
    auto cancelled = session();
    REQUIRE(cancelled->step(1));
    REQUIRE(cancelled->request_stop());
    REQUIRE_FALSE(cancelled->step());
    auto released = cancelled->release();
    REQUIRE(released);
    REQUIRE(released.value().quiescent);
    REQUIRE(released.value().released_state_bytes > 0);
    REQUIRE(cancelled->release().value().released_state_bytes == 0);
    auto graceful = session();
    REQUIRE_FALSE(graceful->request_stop(true));
    NativeOptions options;
    options.allow_partial_output = true;
    graceful = session(options);
    prefill(*graceful);
    REQUIRE(graceful->request_stop(true));
    REQUIRE(graceful->state().stage == NativeStage::completing);
    REQUIRE(graceful->release());
}
TEST_CASE("B-REAL04 model ownership shared sessions and independent instances", "[native][cpu]") {
    auto weights = model();
    std::weak_ptr<const TinyModel> weak = weights;
    auto first = NativeSession::create(weights, make_cpu_compute(), {}, {}, "a");
    auto second = NativeSession::create(weights, make_cpu_compute(), {}, {}, "b");
    REQUIRE(first);
    REQUIRE(second);
    weights.reset();
    REQUIRE(first.value()->request_stop());
    REQUIRE(first.value()->release());
    REQUIRE_FALSE(weak.expired());
    REQUIRE(second.value()->step());
    REQUIRE(second.value()->request_stop());
    REQUIRE(second.value()->release());
    REQUIRE(weak.expired());
    auto third = session();
    REQUIRE(third->step());
}
TEST_CASE("B-REAL05 unqualified controls reject", "[native][cpu]") {
    auto native = session();
    REQUIRE_FALSE(native->profile().offload);
    REQUIRE_FALSE(native->profile().snapshot);
    REQUIRE_FALSE(native->profile().rewind);
    REQUIRE_FALSE(native->profile().batching);
    REQUIRE_FALSE(native->profile().partial_step);
    for (auto operation : {"offload", "snapshot", "rewind", "batch", "mid_kernel_abort"})
        REQUIRE_FALSE(native->unsupported_control(operation));
}
TEST_CASE("B-REAL06 B-INPUT01 injection preserves pending token RNG output state exactly once",
          "[native][cpu]") {
    NativeOptions options;
    options.injection_slot = true;
    options.max_output_tokens = 20;
    options.sampling.temperature = 0.7F;
    options.sampling.seed = 90;
    auto native = session(options);
    prefill(*native);
    REQUIRE(native->step());
    auto before = native->causal_state();
    REQUIRE_FALSE(native->inject("\xff", 88));
    REQUIRE(native->causal_state() == before);
    REQUIRE_FALSE(native->request_stop(true));
    REQUIRE(native->causal_state() == before);
    REQUIRE(native->state().valid);
    const auto pending = before.pending;
    auto pause = native->pause();
    REQUIRE(pause);
    REQUIRE(native->inject("approved 日本語", 17));
    REQUIRE(native->causal_state().evaluated ==
            before.evaluated); // Paused injection performs no useful computation.
    REQUIRE(native->causal_state().pending == pending);
    REQUIRE(native->causal_state().rng == before.rng);
    REQUIRE(native->causal_state().output == before.output);
    REQUIRE(native->causal_state().decoder == before.decoder);
    REQUIRE(native->causal_state().stop_tail == before.stop_tail);
    auto injected = native->causal_state();
    REQUIRE(native->inject("approved 日本語", 17));
    REQUIRE(native->causal_state() == injected);
    REQUIRE(native->resume(native->state().pins, pause.value()));
    auto step = native->step(1);
    REQUIRE(step);
    REQUIRE_FALSE(step.value().token);
    REQUIRE(native->causal_state().evaluated.back() == *pending);
    REQUIRE(native->causal_state().rng_draws == before.rng_draws);
    prefill(*native);
    REQUIRE(native->causal_state().rng_draws == before.rng_draws);
    REQUIRE(native->step());
    REQUIRE(native->causal_state().rng_draws == before.rng_draws + 1);
    auto fresh = session(options);
    REQUIRE(fresh->inject("without pending", 1));
    prefill(*fresh);
    REQUIRE(fresh->causal_state().rng_draws == 0);
    options.sampling.literal_grammar = "x";
    REQUIRE_FALSE(NativeSession::create(model(), make_cpu_compute(), {}, {}, "a", options));
}
TEST_CASE("B-REAL07 strict registered Unicode byte vectors and conversion boundaries",
          "[native][cpu]") {
    for (std::string input : {"日本語", "😀", "👩‍💻", "❤️", "👍🏽", "🇯🇵", "が", "が"}) {
        auto tokens = tokenize(input, {}, 128);
        REQUIRE(tokens);
        REQUIRE(tokens.value().size() == input.size());
        REQUIRE(detokenize(tokens.value(), {}).value() == input);
        Utf8Decoder decoder;
        std::string decoded;
        for (auto token : tokens.value()) {
            char byte = static_cast<char>(token);
            auto text = decoder.append(std::string_view(&byte, 1));
            REQUIRE(text);
            decoded += text.value();
        }
        REQUIRE(decoder.append({}, true));
        REQUIRE(decoded == input);
    }
    REQUIRE(tokenize("日本語", {}, 9).value() ==
            std::vector<TokenId>{230, 151, 165, 230, 156, 172, 232, 170, 158});
    REQUIRE(tokenize("が", {}, 16).value() != tokenize("が", {}, 16).value());
    REQUIRE_FALSE(tokenize("日本語", {}, 8));
    for (std::string bad : {std::string("\xc0\x80", 2), std::string("\xed\xa0\x80", 3),
                            std::string("\xf4\x90\x80\x80", 4), std::string("\xe3", 1)})
        REQUIRE_FALSE(tokenize(bad, {}, 128));
    Utf8Decoder decoder;
    REQUIRE(decoder.append("\xf0\x9f"));
    REQUIRE_FALSE(decoder.append({}, true));
    REQUIRE(decoder.carry == "\xf0\x9f");
    REQUIRE(utf16_to_utf8(u"日本語😀", 128).value() == "日本語😀");
    REQUIRE_FALSE(utf16_to_utf8(std::u16string(1, 0xd800), 128));
    REQUIRE_FALSE(utf16_to_utf8(std::u16string(1, 0xdc00), 128));
    auto collision = TokenizerDefinition{};
    collision.eos = 97;
    REQUIRE_FALSE(validate_tokenizer(collision));
    REQUIRE(detokenize(tokenize("<bos><eos>", {}, 128).value(), {}).value() == "<bos><eos>");
}
TEST_CASE("B-REAL07 literal grammar split emoji carry preserved through pause and output stop",
          "[native][cpu]") {
    NativeOptions options;
    options.max_output_tokens = 64;
    options.sampling.literal_grammar = "👩‍💻日本語STOPafter";
    options.stop_sequences = {"STOP"};
    auto native = session(options);
    prefill(*native);
    REQUIRE(native->step());
    REQUIRE(native->causal_state().output.empty());
    REQUIRE(native->causal_state().decoder.carry == "\xf0");
    auto copy = native->causal_state();
    auto generation = native->pause();
    REQUIRE(generation);
    REQUIRE(native->resume(native->state().pins, generation.value()));
    REQUIRE(native->causal_state() == copy);
    finish(*native);
    REQUIRE(native->causal_state().output == "👩‍💻日本語STOP");
    REQUIRE(native->causal_state().stop_matched);
    REQUIRE(native->causal_state().grammar_position ==
            std::string("👩‍💻日本語STOP").size());
}
