# No network operations belong in configuration. Provisioned upstream sources are
# reviewed and checksum-pinned in dependencies.lock.json before CMake is invoked.
function(flamoris_verify_file path expected)
    if(NOT EXISTS "${PROJECT_SOURCE_DIR}/${path}")
        message(FATAL_ERROR "Missing provisioned dependency ${path}; restore reviewed third_party sources")
    endif()
    file(SHA256 "${PROJECT_SOURCE_DIR}/${path}" actual)
    if(NOT actual STREQUAL expected)
        message(FATAL_ERROR "Dependency checksum mismatch: ${path}; review the dependency lock")
    endif()
endfunction()
flamoris_verify_file(third_party/catch2/catch_amalgamated.hpp 8730587447e16531b832407bbf66959e97ad09af445adc118d2df13689dfecab)
flamoris_verify_file(third_party/catch2/catch_amalgamated.cpp d90d5101269efb3bba00729b8cf14d44a6e6d9b695f9e5c9b4a71345a3bceb99)
flamoris_verify_file(third_party/catch2/LICENSE.txt c9bff75738922193e67fa726fa225535870d2aa1059f91452c411736284ad566)
flamoris_verify_file(third_party/nlohmann/json.hpp aaf127c04cb31c406e5b04a63f1ae89369fccde6d8fa7cdda1ed4f32dfc5de63)
if(WIN32)
    find_package(OpenSSL 3.6 REQUIRED COMPONENTS Crypto)
    if(NOT OPENSSL_VERSION STREQUAL "3.6.4" AND NOT OPENSSL_VERSION STREQUAL "3.6.5")
        message(FATAL_ERROR "Unreviewed Windows OpenSSL version: ${OPENSSL_VERSION}")
    endif()
else()
    find_package(OpenSSL 3.0.13 EXACT REQUIRED COMPONENTS Crypto)
endif()

if(FLAMORIS_LOCKED_TOOLCHAIN AND UNIX AND NOT APPLE)
    file(READ "${PROJECT_SOURCE_DIR}/cmake/dependencies.lock.json" dependency_lock)
    string(JSON reviewed_crypto_hash GET "${dependency_lock}" openssl linux libcrypto_sha256)
    set(reviewed_crypto_hashes "${reviewed_crypto_hash}")
    string(JSON update_count LENGTH "${dependency_lock}" openssl linux reviewed_security_updates)
    if(update_count GREATER 0)
        math(EXPR update_last "${update_count} - 1")
        foreach(index RANGE 0 ${update_last})
            string(JSON update_hash GET "${dependency_lock}" openssl linux reviewed_security_updates ${index} libcrypto_sha256)
            list(APPEND reviewed_crypto_hashes "${update_hash}")
        endforeach()
    endif()
    file(SHA256 "${OPENSSL_CRYPTO_LIBRARY}" crypto_hash)
    if(NOT crypto_hash IN_LIST reviewed_crypto_hashes)
        message(FATAL_ERROR "libcrypto security package differs from the locked Linux dependency. Provision the reviewed package before configure.")
    endif()
elseif(NOT FLAMORIS_LOCKED_TOOLCHAIN)
    message(STATUS "Developer dependency build: exact upstream OpenSSL version matched; distribution security package is not qualified until the locked lane passes")
endif()
