if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 13 OR NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 14)
        message(FATAL_ERROR "Reviewed GNU lane requires GCC 13; no language downgrade is allowed")
    endif()
    set(FLAMORIS_REVIEWED_COMPILER 13.3.0)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS 18 OR NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 19)
        message(FATAL_ERROR "Reviewed Clang lane requires Clang 18")
    endif()
    set(FLAMORIS_REVIEWED_COMPILER 18.1.3)
elseif(MSVC)
    if(MSVC_VERSION LESS 1940 OR MSVC_VERSION GREATER_EQUAL 2000)
        message(FATAL_ERROR "Reviewed Windows lane requires Visual Studio 2022 17.10 or later 17.x")
    endif()
    set(FLAMORIS_REVIEWED_COMPILER "19.40.33811.0")
else()
    message(FATAL_ERROR "Unsupported compiler: select a reviewed GCC 13, Clang 18, or MSVC 17.x lane")
endif()
if(FLAMORIS_LOCKED_TOOLCHAIN AND NOT CMAKE_CXX_COMPILER_VERSION VERSION_EQUAL FLAMORIS_REVIEWED_COMPILER)
    message(FATAL_ERROR "Compiler patch changed: expected ${FLAMORIS_REVIEWED_COMPILER}, found ${CMAKE_CXX_COMPILER_VERSION}. Review the toolchain lock.")
endif()

function(flamoris_sanitizer target)
    if(FLAMORIS_SANITIZER STREQUAL "none")
        return()
    elseif(MSVC)
        message(FATAL_ERROR "The reviewed sanitizer lanes use Clang on Linux")
    elseif(FLAMORIS_SANITIZER STREQUAL "address-undefined")
        target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
        target_link_options(${target} PUBLIC -fsanitize=address,undefined)
    elseif(FLAMORIS_SANITIZER STREQUAL "thread")
        target_compile_options(${target} PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
        target_link_options(${target} PUBLIC -fsanitize=thread)
    else()
        message(FATAL_ERROR "Unknown sanitizer profile: ${FLAMORIS_SANITIZER}")
    endif()
endfunction()

function(flamoris_target target)
    target_include_directories(${target} PUBLIC "${PROJECT_SOURCE_DIR}/include")
    target_compile_features(${target} PUBLIC cxx_std_20)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /permissive- /utf-8)
        if(FLAMORIS_WARNINGS_AS_ERRORS)
            target_compile_options(${target} PRIVATE /WX)
        endif()
    else()
        target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
        if(FLAMORIS_WARNINGS_AS_ERRORS)
            target_compile_options(${target} PRIVATE -Werror)
        endif()
    endif()
    flamoris_sanitizer(${target})
endfunction()

function(flamoris_test source label)
    file(RELATIVE_PATH relative "${PROJECT_SOURCE_DIR}/tests" "${source}")
    string(REGEX REPLACE "[^A-Za-z0-9_]" "_" name "${relative}")
    add_executable(${name} "${source}")
    flamoris_target(${name})
    target_include_directories(${name} PRIVATE "${PROJECT_SOURCE_DIR}/tests")
    target_compile_definitions(${name} PRIVATE
        FLAMORIS_SOURCE_DIR="${PROJECT_SOURCE_DIR}"
        FLAMORIS_TEST_SOURCE_DIR="${PROJECT_SOURCE_DIR}"
        FLAMORIS_TEST_FIXTURE_DIR="${PROJECT_SOURCE_DIR}/tests/fixtures")
    if(relative STREQUAL "unit/domain_tests.cpp")
        target_link_libraries(${name} PRIVATE flamoris_runtime_domain Catch2::Catch2WithMain)
    else()
        target_link_libraries(${name} PRIVATE flamoris::runtime Catch2::Catch2WithMain Threads::Threads)
    endif()
    add_test(NAME ${name} COMMAND ${name})
    set_tests_properties(${name} PROPERTIES LABELS "${label}" WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}" TIMEOUT 60)
endfunction()
